resource:
  people:
    resources:
      happiness:
        production_per_step: 10
        step_size: 100
      civilization:
        bonus: 10
        step_size: 50
  wood:
    buildings:
      woodcutter:
        production: 100
        production_quotient: 1.1
      sawmill:
        bonus: 50
  stone:
  iron:
  gold:
  crop:
    buildings:
      farm:
        production: 50
        production_quotient: 2
      lumbermill:
        bonus: 10
        bonus_qutient: 2
