<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginCountry extends BaseCountry
{
  public static function onActivateCreateNew(sfEvent $event)
  {
    $user = $event['user'];
    
    $country = new Country();
    $country->name = "{$user->login}'s empire";
    
    $position = Position::useFirstFreePosition();
    $name = "Capital of {$country->name}";
    $type = 'capital';
    
    $country->foundCapital($position, $name);
    
    $user->Country[0] = $country;
     
    $user->save();
  }
  
  public function foundCapital($position, $name = '')
  {
    $position = array(
      'x' => $position->x * 10,
      'y' => $position->y * 10
    );
    
    Settlement::foundNew($this, $position, $name, 'capital');
  }
  
  public function listSettlements()
  {
    $q = Doctrine_Query::create()
      ->from('Country c')
      ->leftJoin('c.Settlement s')
      ->where('c.id = ?', $this->id);
      
    return $q->fetchOne()->Settlement;
  }
}