<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginSettlement extends BaseSettlement
{
  public function getPosition()
  {
    return Doctrine_Query::create()
      ->select('f.x, f.y')
      ->from('Field f')
      ->leftJoin('f.Settlement s')
      ->where('s.id = ?', $this->id)
      ->andWhere('f.type = ?', 'city')
      ->fetchOne();
  }
  
  public static function foundNew(Country $country, $position, $name = '', $type = 'village', $parentSettlement = null)
  {  
    if (!$name) {
      $name = "New $type";
    }
    
    $settlement = new Settlement();
    $settlement->name = $name;
    $settlement->type = $type;
    
    if($parentSettlement instanceof Settlement)
    {
      $settlement->ParentSettlement = $parentSettlement;
    }
    
    $i = 0;
    
    $fieldList = self::getSettlementFieldList($position['x'], $position['y']);
    
    foreach ($fieldList as $x => $tempFieldList)
    {
      foreach ($tempFieldList as $y => $type)
      {
        $settlement->Field[$i]->x = $x + $position['x'];
        $settlement->Field[$i]->y = $y + $position['y'];
        $settlement->Field[$i]->type = $type;
        $i++;
      }
    }
    
    $settlement->last_checked = time();
    
    $country->Settlement[] = $settlement;
  }
  
  protected static function getSettlementFieldList($x, $y)
  {
    $fieldList = self::getFieldList();
    $usedList = self::getUsedFieldList($x, $y);
    
    foreach ($usedList as $used)
    {
      unset($fieldList[$used->x - $x][$used->y - $y]);
    }
    
    foreach ($fieldList as $key => $value)
    {
      if (!$value)
      {
        unset($fieldList[$key]);
      }
    }
    
    return $fieldList;
  }
  
  protected static function getFieldList()
  {
    return array(
      '-3' => array(
        '-1' => 'blank',
        '0'  => 'blank',
        '1'  => 'blank'
      ),
      '-2' => array(
        '-2' => 'blank',
        '-1' => 'blank',
        '0'  => 'blank',
        '1'  => 'blank',
        '2'  => 'blank'
      ),
      '-1' => array(
        '-3' => 'blank',
        '-2' => 'blank',
        '-1' => 'blank',
        '0'  => 'blank',
        '1'  => 'blank',
        '2'  => 'blank',
        '3'  => 'blank'
      ),
      '0' => array(
        '-3' => 'blank',
        '-2' => 'blank',
        '-1' => 'blank',
        '0'  => 'city',
        '1'  => 'blank',
        '2'  => 'blank',
        '3'  => 'blank'
      ),
      '1' => array(
        '-3' => 'blank',
        '-2' => 'blank',
        '-1' => 'blank',
        '0'  => 'blank',
        '1'  => 'blank',
        '2'  => 'blank',
        '3'  => 'blank'
      ),
      '2' => array(
        '-2' => 'blank',
        '-1' => 'blank',
        '0'  => 'blank',
        '1'  => 'blank',
        '2'  => 'blank'
      ),
      '3' => array(
        '-1' => 'blank',
        '0'  => 'blank',
        '1'  => 'blank'
      )
    );
  }
  
  protected static function getUsedFieldList($x, $y)
  {
    $q = Doctrine_Query::create()
      ->select('f.x, f.y')
      ->from('Field f')
      ->where("sqrt(abs((x - $x) * (x - $x) + (y - $y) * (y - $y))) < 3.17")
      ->orderby('f.id')
      ->execute();
    return $q;
  }
}