settlement_production_field:
  url:    /settlement/:settlement_id/production/:field_id
  param: { module: settlement, action: productionField }
  requirements: { settlement_id: \d+, field_id: \d+ }

settlement_production_area:
  url:   /settlement/:id/production
  param: { module: settlement, action: productionArea }
  requirements: { id: \d+ }
  
settlement_defences_area:
  url:   /settlement/:id/defences
  param: { module: settlement, action: defencesArea }
  requirements: { id: \d+ }

settlement_city_area:
  url:   /settlement/:id/city
  param: { module: settlement, action: cityArea }
  requirements: { id: \d+ }

settlement_square_area:
  url:   /settlement/:id/square
  param: { module: settlement, action: squareArea }
  requirements: { id: \d+ }

found_settlement:
  url:   /settlement/:id/found_new
  param: { module: settlement, action: found }
  requirements: 
    id: \d+

settlement:
  url:   /settlement/:id
  param: { module: settlement, action: productionArea }
  requirements: { id: \d+ }

country_map:
  url:   /country
  param: { module: map, action: country }
  
world_map:
  url:   /world
  param: { module: map, action: world, x: default, y: default }

world_map_by_position:
  url: /world/:x/:y
  param: { module: map, action: world }
  requirements: { x: -?\d+, y: -?\d+ }

login:
  url:   /login
  param: { module: user, action: login}
  
register:
  url:   /register
  param: { module: user, action: register }
  
logout:
  url:   /logout
  param: { module: user, action: logout }

# default rules
homepage:
  url:   /
  param: { module: map, action: country }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
