found_settlement:
  url:   /settlement/:id/found_new
  param: { module: settlement, action: found }
  requirements: 
    id: \d+

settlement:
  url:   /settlement/:id
  param: { module: settlement, action: resources }
  requirements: { id: \d+ }

country_map:
  url:   /country
  param: { module: map, action: country }
  
world_map:
  url:   /world
  param: { module: map, action: world, x: default, y: default }

world_map_by_position:
  url: /world/:x/:y
  param: { module: map, action: world }
  requirements: { x: -?\d+, y: -?\d+ }

login:
  url:   /login
  param: { module: user, action: login}
  
register:
  url:   /register
  param: { module: user, action: register }
  
logout:
  url:   /logout
  param: { module: user, action: logout }

# default rules
homepage:
  url:   /
  param: { module: map, action: country }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
